"""
环保行业标准大规模种子数据脚本
覆盖：化工/石化/医药/农药/有机化学 行业
覆盖：废气/废水/固废/大气综合/污水排放/雨水/地表水/水环境/噪声/土壤/地下水/环境空气/有毒有害/职业病危害
"""
from datetime import datetime
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.db.database import SessionLocal
from app.db.models import Standard, PollutionFactor, PollutionLimit


def seed_all():
    db = SessionLocal()
    try:
        # ==================== 污染因子 ====================
        factor_map = {}
        factors = [
            ("化学需氧量", "COD", "mg/L"),
            ("氨氮", "NH3-N", "mg/L"),
            ("悬浮物", "SS", "mg/L"),
            ("石油类", "石油类", "mg/L"),
            ("挥发酚", "挥发酚", "mg/L"),
            ("氰化物", "氰化物", "mg/L"),
            ("总汞", "Hg", "μg/L"),
            ("总砷", "As", "mg/L"),
            ("总铅", "Pb", "mg/L"),
            ("总镉", "Cd", "mg/L"),
            ("总铬", "Cr", "mg/L"),
            ("六价铬", "Cr6+", "mg/L"),
            ("总铜", "Cu", "mg/L"),
            ("总锌", "Zn", "mg/L"),
            ("总镍", "Ni", "mg/L"),
            ("总银", "Ag", "mg/L"),
            ("总铝", "Al", "mg/L"),
            ("阴离子表面活性剂", "LAS", "mg/L"),
            ("硫化物", "S2-", "mg/L"),
            ("氟化物", "F-", "mg/L"),
            ("磷酸盐(以P计)", "PO43-", "mg/L"),
            ("苯胺类", "苯胺类", "mg/L"),
            ("硝基苯类", "硝基苯类", "mg/L"),
            ("苯并[a]芘", "BaP", "ng/L"),
            ("多环芳烃", "PAHs", "mg/L"),
            ("甲醛", "HCHO", "mg/m3"),
            ("苯", "C6H6", "mg/m3"),
            ("甲苯", "C7H8", "mg/m3"),
            ("二甲苯", "C8H10", "mg/m3"),
            ("苯乙烯", "C8H8", "mg/m3"),
            ("酚类", "酚类", "mg/m3"),
            ("挥发性有机物", "VOCs", "mg/m3"),
            ("非甲烷总烃", "NMHC", "mg/m3"),
            ("二氧化硫", "SO2", "mg/m3"),
            ("氮氧化物", "NOx", "mg/m3"),
            ("颗粒物", "PM", "mg/m3"),
            ("烟尘", "烟尘", "mg/m3"),
            ("氟化物", "F", "mg/m3"),
            ("氯化氢", "HCl", "mg/m3"),
            ("氯气", "Cl2", "mg/m3"),
            ("氨", "NH3", "mg/m3"),
            ("恶臭", "臭气浓度", "无量纲"),
            ("硫酸雾", "H2SO4", "mg/m3"),
            ("硝酸雾", "HNO3", "mg/m3"),
            ("铬酸雾", "铬酸雾", "mg/m3"),
            ("苯并[a]芘", "B[a]P", "ng/m3"),
            ("二噁英类", "二噁英", "ng/m3"),
            ("汞及其化合物", "Hg(化合)", "μg/m3"),
            ("铅及其化合物", "Pb(化合)", "μg/m3"),
            ("镉及其化合物", "Cd(化合)", "μg/m3"),
            ("砷及其化合物", "As(化合)", "μg/m3"),
            ("铍及其化合物", "Be(化合)", "μg/m3"),
            ("铊及其化合物", "Tl(化合)", "μg/m3"),
            ("锑及其化合物", "Sb(化合)", "μg/m3"),
            ("锡及其化合物", "Sn(化合)", "μg/m3"),
            ("铜及其化合物", "Cu(化合)", "μg/m3"),
            ("锌及其化合物", "Zn(化合)", "μg/m3"),
            ("钴及其化合物", "Co(化合)", "μg/m3"),
            ("碘化氢", "HI", "mg/m3"),
            ("甲磺酸", "甲磺酸", "mg/m3"),
            ("乙磺酸", "乙磺酸", "mg/m3"),
            ("噪声", "噪声", "dB(A)"),
            ("pH值", "pH", "无量纲"),
            ("水温", "水温", "℃"),
            ("溶解氧", "DO", "mg/L"),
            ("高锰酸盐指数", "CODMn", "mg/L"),
            ("BOD5", "BOD5", "mg/L"),
            ("总有机碳", "TOC", "mg/L"),
            ("总氮", "TN", "mg/L"),
            ("总磷", "TP", "mg/L"),
            ("色度", "色度", "倍"),
            ("动植物油", "动植物油", "mg/L"),
            ("阴离子表面活性剂", "阴离子表面活性剂", "mg/L"),
            ("总余氯(以Cl计)", "余氯", "mg/L"),
            ("三氯甲烷", "三氯甲烷", "μg/L"),
            ("四氯化碳", "四氯化碳", "μg/L"),
            ("三溴甲烷", "三溴甲烷", "μg/L"),
            ("二氯苯", "二氯苯", "mg/L"),
            ("五氯酚", "五氯酚", "mg/L"),
            ("甲醛", "甲醛", "mg/L"),
            ("苯", "苯", "mg/L"),
            ("甲苯", "甲苯", "mg/L"),
            ("二甲苯", "二甲苯", "mg/L"),
            ("氯苯", "氯苯", "mg/L"),
            ("硝基苯", "硝基苯", "mg/L"),
            ("苯胺", "苯胺", "mg/L"),
            ("联苯胺", "联苯胺", "mg/L"),
            ("丙烯腈", "丙烯腈", "mg/L"),
            ("丙烯醛", "丙烯醛", "mg/L"),
            ("乐果", "乐果", "mg/L"),
            ("敌敌畏", "敌敌畏", "mg/L"),
            ("对硫磷", "对硫磷", "mg/L"),
            ("甲基对硫磷", "甲基对硫磷", "mg/L"),
            ("马拉硫磷", "马拉硫磷", "mg/L"),
            ("五氯酚钠", "五氯酚钠", "mg/L"),
            ("草甘膦", "草甘膦", "mg/L"),
            ("多菌灵", "多菌灵", "mg/L"),
            ("毒死蜱", "毒死蜱", "mg/L"),
            ("草甘膦铵盐", "草甘膦铵盐", "mg/L"),
            ("敌草快", "敌草快", "mg/L"),
            ("溴甲烷", "溴甲烷", "mg/L"),
            ("总α放射性", "总α", "Bq/L"),
            ("总β放射性", "总β", "Bq/L"),
            ("总镭", "Ra", "Bq/L"),
            ("放射性锶", "Sr-90", "Bq/L"),
            ("放射性铯", "Cs-137", "Bq/L"),
            ("放射性碘", "I-131", "Bq/L"),
            ("阴离子合成洗涤剂", "阴离子合成洗涤剂", "mg/L"),
        ]
        for name, symbol, unit in factors:
            existing = db.query(PollutionFactor).filter(PollutionFactor.symbol == symbol).first()
            if not existing:
                pf = PollutionFactor(name=name, symbol=symbol, unit=unit)
                db.add(pf)
                factor_map[symbol] = pf.id
            else:
                factor_map[symbol] = existing.id
        db.commit()
        print(f"污染因子: {len(factor_map)} 个")

        # ==================== 标准数据 ====================
        standards = [
            # ====== 废气排放标准 ======
            # 大气综合
            Standard(title="GB 16297-1996 大气污染物综合排放标准", standard_type="综合标准", industry="general",
                     category="废气", sub_category="大气综合",
                     publish_date=datetime(1996, 11, 1), implement_date=datetime(1997, 1, 1),
                     content="规定了33种大气污染物的排放高度、排放速率和浓度限值，适用于现有工业企业大气污染物排放管理。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 石化
            Standard(title="GB 31570-2015 石油化学工业污染物排放标准", standard_type="行业标准", industry="石化",
                     category="废气", sub_category="石化废气",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了石油化学工业企业水平台和大气污染物排放限值，适用于石油化学工业生产企业排放的大气污染物控制。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 31571-2015 石油化工工业污染物排放标准", standard_type="行业标准", industry="石化",
                     category="废气", sub_category="石化废气",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了石油化工工业企业大气污染物排放限值，适用于石油化工工业企业排放的大气污染物控制。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 31572-2015 石油炼制工业污染物排放标准", standard_type="行业标准", industry="石化",
                     category="废气", sub_category="石油炼制废气",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了石油炼制工业企业大气污染物排放限值，适用于石油炼制工业企业排放的大气污染物控制。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 化工
            Standard(title="GB 31573-2015 无机化学工业污染物排放标准", standard_type="行业标准", industry="化工",
                     category="废气", sub_category="化工废气",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了无机化学工业企业大气污染物排放限值，适用于无机化学工业企业排放的大气污染物控制。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 31574-2015 染料工业污染物排放标准", standard_type="行业标准", industry="化工",
                     category="废气", sub_category="染料工业废气",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了染料工业企业大气污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 31575-2015 炼焦化学工业污染物排放标准", standard_type="行业标准", industry="化工",
                     category="废气", sub_category="炼焦废气",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了炼焦化学工业企业大气污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 31576-2015 农药工业污染物排放标准", standard_type="行业标准", industry="农药",
                     category="废气", sub_category="农药废气",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了农药工业企业大气污染物排放限值，适用于农药制造行业。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 31577-2016 橡胶和塑料制品工业污染物排放标准", standard_type="行业标准", industry="化工",
                     category="废气", sub_category="橡胶塑料制品废气",
                     publish_date=datetime(2016, 6, 22), implement_date=datetime(2016, 12, 1),
                     content="规定了橡胶和塑料制品工业企业大气污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 31578-2016 煤炭化工产品污染物排放标准", standard_type="行业标准", industry="化工",
                     category="废气", sub_category="煤化工废气",
                     publish_date=datetime(2016, 6, 22), implement_date=datetime(2016, 12, 1),
                     content="规定了煤炭化工产品生产工业企业大气污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 医药
            Standard(title="GB 31579-2015 医药合成类、医药中间体、农药类等工业污染物排放标准", standard_type="行业标准", industry="医药",
                     category="废气", sub_category="医药工业废气",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了医药合成类、医药中间体、农药类等工业企业大气污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 31579-2015 医药工业污染物排放标准（合成药、原料药、中药）", standard_type="行业标准", industry="医药",
                     category="废气", sub_category="医药工业废气",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了医药合成类、医药中间体、农药类等工业企业大气污染物排放限值。适用于医药工业生产企业排放的大气污染物控制。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 有机化学
            Standard(title="GB 31572-2015 石油炼制工业污染物排放标准", standard_type="行业标准", industry="有机化学",
                     category="废气", sub_category="有机化学废气",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了石油炼制工业企业大气污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 工业炉窑
            Standard(title="GB 9078-1996 工业炉窑大气污染物排放标准", standard_type="综合标准", industry="general",
                     category="废气", sub_category="工业炉窑",
                     publish_date=datetime(1996, 11, 1), implement_date=datetime(1997, 1, 1),
                     content="规定了工业炉窑大气污染物排放标准，适用于各种工业炉窑。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 锅炉
            Standard(title="GB 13271-2014 锅炉大气污染物排放标准", standard_type="综合标准", industry="general",
                     category="废气", sub_category="锅炉废气",
                     publish_date=datetime(2014, 7, 9), implement_date=datetime(2014, 7, 1),
                     content="规定了锅炉烟气中颗粒物、SO2、NOx、汞及其化合物的最高允许排放浓度和烟气黑度限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 恶臭
            Standard(title="GB 14554-93 恶臭污染物排放标准", standard_type="综合标准", industry="general",
                     category="废气", sub_category="恶臭",
                     publish_date=datetime(1993, 10, 7), implement_date=datetime(1994, 2, 1),
                     content="规定了恶臭污染物排放限值，适用于恶臭污染物排放管理。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # VOCs
            Standard(title="GB 37822-2019 挥发性有机物无组织排放控制标准", standard_type="综合标准", industry="general",
                     category="废气", sub_category="VOCs",
                     publish_date=datetime(2019, 5, 10), implement_date=datetime(2019, 7, 1),
                     content="规定了VOCs无组织排放控制要求、限值及监测要求。适用于VOCs物料存储、转移和输送、废气收集、废气处理设施等环节。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 表面处理
            Standard(title="GB 31578-2015 表面涂装（汽车制造业）挥发性有机物排放标准", standard_type="行业标准", industry="general",
                     category="废气", sub_category="表面处理",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了汽车制造业表面涂装过程挥发性有机物排放标准。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 水泥
            Standard(title="GB 4915-2013 水泥工业大气污染物排放标准", standard_type="行业标准", industry="general",
                     category="废气", sub_category="水泥工业",
                     publish_date=datetime(2013, 12, 31), implement_date=datetime(2014, 7, 1),
                     content="规定了水泥工业大气污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 钢铁
            Standard(title="GB 28662-2012 钢铁烧结球团工业大气污染物排放标准", standard_type="行业标准", industry="钢铁",
                     category="废气", sub_category="钢铁工业",
                     publish_date=datetime(2012, 12, 31), implement_date=datetime(2013, 7, 1),
                     content="规定了钢铁烧结球团工业大气污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 玻璃
            Standard(title="GB 26453-2011 玻璃工业大气污染物排放标准", standard_type="行业标准", industry="建材",
                     category="废气", sub_category="玻璃工业",
                     publish_date=datetime(2011, 10, 28), implement_date=datetime(2012, 2, 1),
                     content="规定了玻璃工业大气污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 铅锌冶炼
            Standard(title="GB 25466-2010 铅、锌工业污染物排放标准", standard_type="行业标准", industry="有色冶金",
                     category="废气", sub_category="铅锌冶炼废气",
                     publish_date=datetime(2010, 10, 28), implement_date=datetime(2011, 2, 1),
                     content="规定了铅、锌工业企业大气污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 铜冶炼
            Standard(title="GB 25467-2010 铜、镍、钴工业污染物排放标准", standard_type="行业标准", industry="有色冶金",
                     category="废气", sub_category="铜冶炼废气",
                     publish_date=datetime(2010, 10, 28), implement_date=datetime(2011, 2, 1),
                     content="规定了铜、镍、钴工业企业大气污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 铝冶炼
            Standard(title="GB 25468-2010 铝工业污染物排放标准", standard_type="行业标准", industry="有色冶金",
                     category="废气", sub_category="铝冶炼废气",
                     publish_date=datetime(2010, 10, 28), implement_date=datetime(2011, 2, 1),
                     content="规定了铝工业企业大气污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 危险废物焚烧
            Standard(title="GB 18484-2001 危险废物焚烧污染控制标准", standard_type="综合标准", industry="固废处理",
                     category="废气", sub_category="危废焚烧",
                     publish_date=datetime(2001, 4, 30), implement_date=datetime(2001, 12, 1),
                     content="规定了危险废物焚烧炉大气污染物排放限值，适用于危险废物焚烧设施。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 危险废物贮存
            Standard(title="GB 18597-2023 危险废物贮存污染控制标准", standard_type="综合标准", industry="固废处理",
                     category="废气", sub_category="危废贮存",
                     publish_date=datetime(2023, 7, 10), implement_date=datetime(2023, 8, 1),
                     content="规定了危险废物贮存设施的大气污染物排放要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 医疗卫生
            Standard(title="GB 18483-2001 饮食业油烟排放标准", standard_type="综合标准", industry="general",
                     category="废气", sub_category="油烟",
                     publish_date=datetime(2001, 4, 30), implement_date=datetime(2002, 1, 1),
                     content="规定了饮食业油烟排放标准。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 废水排放标准 ======
            # 污水综合排放
            Standard(title="GB 8978-1996 污水综合排放标准", standard_type="综合标准", industry="general",
                     category="废水", sub_category="污水排放",
                     publish_date=datetime(1996, 10, 4), implement_date=datetime(1997, 1, 1),
                     content="规定了水污染物排放限值，将污染物分为第一类和第二类，第一类污染物不分行业和污水排放方式，也不分受纳水体的功能类别，一律在车间或车间处理设施排放口采样。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 石化
            Standard(title="GB 31570-2015 石油化学工业污染物排放标准", standard_type="行业标准", industry="石化",
                     category="废水", sub_category="石化废水",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了石油化学工业企业水污染物排放限值，适用于石油化学工业生产企业排放的水污染物控制。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 31571-2015 石油化工工业污染物排放标准", standard_type="行业标准", industry="石化",
                     category="废水", sub_category="石油化工废水",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了石油化工工业企业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 31572-2015 石油炼制工业污染物排放标准", standard_type="行业标准", industry="石化",
                     category="废水", sub_category="石油炼制废水",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了石油炼制工业企业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 化工
            Standard(title="GB 31573-2015 无机化学工业污染物排放标准", standard_type="行业标准", industry="化工",
                     category="废水", sub_category="化工废水",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了无机化学工业企业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 31574-2015 染料工业污染物排放标准", standard_type="行业标准", industry="化工",
                     category="废水", sub_category="染料废水",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了染料工业企业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 31575-2015 炼焦化学工业污染物排放标准", standard_type="行业标准", industry="化工",
                     category="废水", sub_category="炼焦废水",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了炼焦化学工业企业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 农药
            Standard(title="GB 31576-2015 农药工业污染物排放标准", standard_type="行业标准", industry="农药",
                     category="废水", sub_category="农药废水",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了农药工业企业水污染物排放限值，适用于农药制造行业。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 医药
            Standard(title="GB 31579-2015 医药工业污染物排放标准", standard_type="行业标准", industry="医药",
                     category="废水", sub_category="医药废水",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了医药合成类、医药中间体、农药类等工业企业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 有机化学
            Standard(title="GB 31572-2015 有机化学工业污染物排放标准", standard_type="行业标准", industry="有机化学",
                     category="废水", sub_category="有机化学废水",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了有机化学工业生产企业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 造纸
            Standard(title="GB 3544-2008 造纸工业水污染物排放标准", standard_type="行业标准", industry="造纸",
                     category="废水", sub_category="造纸废水",
                     publish_date=datetime(2008, 1, 17), implement_date=datetime(2008, 6, 1),
                     content="规定了造纸工业企业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 电镀
            Standard(title="GB 21900-2008 电镀污染物排放标准", standard_type="行业标准", industry="电镀",
                     category="废水", sub_category="电镀废水",
                     publish_date=datetime(2008, 1, 17), implement_date=datetime(2008, 6, 1),
                     content="规定了电镀工业企业水污染物排放限值，适用于电镀行业。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 纺织
            Standard(title="GB 4287-2012 纺织染整工业水污染物排放标准", standard_type="行业标准", industry="纺织",
                     category="废水", sub_category="纺织废水",
                     publish_date=datetime(2012, 12, 31), implement_date=datetime(2013, 7, 1),
                     content="规定了纺织染整工业企业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 皮革
            Standard(title="GB 31578-2015 制革及毛皮加工工业水污染物排放标准", standard_type="行业标准", industry="皮革",
                     category="废水", sub_category="皮革废水",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了制革及毛皮加工企业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 食品
            Standard(title="GB 13457-92 肉类加工工业水污染物排放标准", standard_type="行业标准", industry="食品",
                     category="废水", sub_category="食品加工废水",
                     publish_date=datetime(1992, 4, 16), implement_date=datetime(1992, 10, 1),
                     content="规定了肉类加工工业企业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # 酿造
            Standard(title="GB 27632-2011 发酵类制药工业水污染物排放标准", standard_type="行业标准", industry="医药",
                     category="废水", sub_category="发酵废水",
                     publish_date=datetime(2011, 10, 28), implement_date=datetime(2012, 2, 1),
                     content="规定了发酵类制药工业企业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 大气环境质量标准 ======
            Standard(title="GB 3095-2012 环境空气质量标准", standard_type="综合标准", industry="general",
                     category="环境空气", sub_category="环境空气质量",
                     publish_date=datetime(2012, 2, 29), implement_date=datetime(2016, 1, 1),
                     content="规定了环境空气中SO2、NO2、CO、O3、PM10、PM2.5等污染物的浓度限值及测量方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 地表水标准 ======
            Standard(title="GB 3838-2002 地表水环境质量标准", standard_type="综合标准", industry="general",
                     category="水环境", sub_category="地表水",
                     publish_date=datetime(2002, 4, 28), implement_date=datetime(2002, 6, 1),
                     content="根据地表水使用功能和保护目标将水域分为五类，规定了各水域的污染物浓度限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 地下水标准 ======
            Standard(title="GB/T 14848-2017 地下水质量标准", standard_type="综合标准", industry="general",
                     category="地下水", sub_category="地下水质量",
                     publish_date=datetime(2017, 11, 16), implement_date=datetime(2018, 1, 1),
                     content="根据地下水使用功能和保护目标将地下水分为五类，规定了各类地下水的污染物浓度限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 雨水标准 ======
            Standard(title="GB 50483-2009 化工建设项目环境保护工程设计规范", standard_type="综合标准", industry="化工",
                     category="废水", sub_category="雨水排放",
                     publish_date=datetime(2009, 11, 4), implement_date=datetime(2010, 3, 1),
                     content="规定了化工建设项目雨水排放系统的设计要求，包括初期雨水收集与处理。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 噪声标准 ======
            Standard(title="GB 12348-2008 工业企业厂界环境噪声排放标准", standard_type="综合标准", industry="general",
                     category="噪声", sub_category="厂界噪声",
                     publish_date=datetime(2008, 7, 16), implement_date=datetime(2008, 10, 1),
                     content="规定了工业企业厂界环境噪声排放限值及测量方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 3096-2008 声环境质量标准", standard_type="综合标准", industry="general",
                     category="噪声", sub_category="声环境",
                     publish_date=datetime(2008, 7, 16), implement_date=datetime(2008, 10, 1),
                     content="根据区域使用功能将声环境功能区分为五类，规定了各类区域的噪声限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 土壤标准 ======
            Standard(title="GB 36600-2018 土壤环境质量 建设用地土壤污染风险管控标准", standard_type="综合标准", industry="general",
                     category="土壤", sub_category="建设用地",
                     publish_date=datetime(2018, 8, 16), implement_date=datetime(2019, 7, 1),
                     content="规定了建设用地土壤污染风险筛选值和管制值，适用于建设用地土壤污染风险管控。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 15618-2018 土壤环境质量 农用地土壤污染风险管控标准", standard_type="综合标准", industry="general",
                     category="土壤", sub_category="农用地",
                     publish_date=datetime(2018, 8, 16), implement_date=datetime(2019, 8, 1),
                     content="规定了农用地土壤污染风险筛选值和管制值，适用于农用地土壤污染风险管控。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 固废标准 ======
            Standard(title="GB 18599-2020 一般工业固体废物贮存和填埋污染控制标准", standard_type="综合标准", industry="general",
                     category="固废", sub_category="一般固废",
                     publish_date=datetime(2020, 1, 9), implement_date=datetime(2020, 7, 1),
                     content="规定了一般工业固体废物贮存、填埋设施的大气、地下水、土壤污染控制要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 18598-2019 危险废物贮存污染控制标准", standard_type="综合标准", industry="固废处理",
                     category="固废", sub_category="危废贮存",
                     publish_date=datetime(2019, 7, 10), implement_date=datetime(2019, 12, 1),
                     content="规定了危险废物贮存设施的大气、地下水、土壤污染控制要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 18484-2001 危险废物焚烧污染控制标准", standard_type="综合标准", industry="固废处理",
                     category="固废", sub_category="危废焚烧",
                     publish_date=datetime(2001, 4, 30), implement_date=datetime(2001, 12, 1),
                     content="规定了危险废物焚烧炉大气污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 18597-2023 危险废物贮存污染控制标准", standard_type="综合标准", industry="固废处理",
                     category="固废", sub_category="危废管理",
                     publish_date=datetime(2023, 7, 10), implement_date=datetime(2023, 8, 1),
                     content="规定了危险废物贮存、转移、处置的污染控制要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 有毒有害物质标准 ======
            Standard(title="GBZ 2.1-2019 工作场所有害因素职业接触限值 第1部分：化学有害因素", standard_type="行业标准", industry="general",
                     category="职业病危害", sub_category="化学有害因素",
                     publish_date=datetime(2019, 11, 28), implement_date=datetime(2020, 2, 1),
                     content="规定了工作场所化学有害因素的PC-TWA、PC-STEL、MAC等职业接触限值。",
                     source_url="https://www.nhc.gov.cn/", status="active"),
            Standard(title="GBZ 2.2-2007 工作场所有害因素职业接触限值 第2部分：物理因素", standard_type="行业标准", industry="general",
                     category="职业病危害", sub_category="物理因素",
                     publish_date=datetime(2007, 8, 1), implement_date=datetime(2007, 11, 1),
                     content="规定了工作场所物理因素的职业接触限值，包括噪声、高温、手传振动等。",
                     source_url="https://www.nhc.gov.cn/", status="active"),
            Standard(title="GBZ 1-2010 工业企业设计卫生标准", standard_type="行业标准", industry="general",
                     category="职业病危害", sub_category="卫生设计",
                     publish_date=datetime(2010, 11, 2), implement_date=datetime(2011, 5, 1),
                     content="规定了工业企业设计中的卫生要求，包括有害因素控制、防护设施等。",
                     source_url="https://www.nhc.gov.cn/", status="active"),
            Standard(title="GBZ/T 229.1-2010 工作场所职业病危害作业分级 第1部分：生产性粉尘", standard_type="行业标准", industry="general",
                     category="职业病危害", sub_category="粉尘分级",
                     publish_date=datetime(2010, 11, 2), implement_date=datetime(2011, 5, 1),
                     content="规定了生产性粉尘作业的危害分级方法。",
                     source_url="https://www.nhc.gov.cn/", status="active"),
            Standard(title="GBZ/T 229.2-2010 工作场所职业病危害作业分级 第2部分：化学因素", standard_type="行业标准", industry="general",
                     category="职业病危害", sub_category="化学因素分级",
                     publish_date=datetime(2010, 11, 2), implement_date=datetime(2011, 5, 1),
                     content="规定了化学因素作业的危害分级方法。",
                     source_url="https://www.nhc.gov.cn/", status="active"),
            Standard(title="GBZ/T 229.3-2010 工作场所职业病危害作业分级 第3部分：高温", standard_type="行业标准", industry="general",
                     category="职业病危害", sub_category="高温分级",
                     publish_date=datetime(2010, 11, 2), implement_date=datetime(2011, 5, 1),
                     content="规定了高温作业的危害分级方法。",
                     source_url="https://www.nhc.gov.cn/", status="active"),
            Standard(title="GBZ/T 229.4-2010 工作场所职业病危害作业分级 第4部分：噪声", standard_type="行业标准", industry="general",
                     category="职业病危害", sub_category="噪声分级",
                     publish_date=datetime(2010, 11, 2), implement_date=datetime(2011, 5, 1),
                     content="规定了噪声作业的危害分级方法。",
                     source_url="https://www.nhc.gov.cn/", status="active"),
            # ====== 环境空气标准 ======
            Standard(title="HJ 2.2-2018 环境影响评价技术导则 大气环境", standard_type="行业标准", industry="general",
                     category="环境空气", sub_category="环评导则",
                     publish_date=datetime(2018, 12, 1), implement_date=datetime(2018, 12, 1),
                     content="规定了大气环境影响评价的技术方法、评价等级和评价范围。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 944-2018 大气污染治理设施运行状况识别技术规范", standard_type="行业标准", industry="general",
                     category="环境空气", sub_category="治理设施",
                     publish_date=datetime(2018, 6, 1), implement_date=datetime(2018, 9, 1),
                     content="规定了大气污染治理设施运行状况的识别方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 水环境标准 ======
            Standard(title="HJ 2.3-2018 环境影响评价技术导则 地表水环境", standard_type="行业标准", industry="general",
                     category="水环境", sub_category="地表水环评",
                     publish_date=datetime(2018, 12, 1), implement_date=datetime(2019, 3, 1),
                     content="规定了地表水环境影响评价的技术方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 2.3-2018 环境影响评价技术导则 地下水环境", standard_type="行业标准", industry="general",
                     category="地下水", sub_category="地下水环评",
                     publish_date=datetime(2018, 12, 1), implement_date=datetime(2019, 3, 1),
                     content="规定了地下水环境影响评价的技术方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 固废标准 ======
            Standard(title="HJ 2035-2013 危险废物收集 贮存 运输技术规范", standard_type="行业标准", industry="固废处理",
                     category="固废", sub_category="危废管理",
                     publish_date=datetime(2013, 10, 1), implement_date=datetime(2014, 2, 1),
                     content="规定了危险废物收集、贮存、运输的技术要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 2037-2013 危险废物排污费征收标准（试行）", standard_type="行业标准", industry="固废处理",
                     category="固废", sub_category="危废管理",
                     publish_date=datetime(2013, 10, 1), implement_date=datetime(2014, 2, 1),
                     content="规定了危险废物排污费征收方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 734-2015 土壤环境监测技术规范", standard_type="行业标准", industry="general",
                     category="土壤", sub_category="监测技术",
                     publish_date=datetime(2015, 9, 25), implement_date=datetime(2016, 2, 1),
                     content="规定了土壤环境监测的技术要求和方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 化工行业标准 ======
            Standard(title="HG/T 20660-2017 化工企业安全卫生设计规范", standard_type="行业标准", industry="化工",
                     category="职业病危害", sub_category="安全卫生",
                     publish_date=datetime(2017, 12, 1), implement_date=datetime(2018, 3, 1),
                     content="规定了化工企业安全卫生设计的通用要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HG/T 20571-2018 化工企业环境保护设计规范", standard_type="行业标准", industry="化工",
                     category="废气", sub_category="环保设计",
                     publish_date=datetime(2018, 5, 1), implement_date=datetime(2018, 9, 1),
                     content="规定了化工企业环境保护设计的技术要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 农药行业标准 ======
            Standard(title="GB/T 19604-2019 农药制造业的环境影响评价技术导则", standard_type="行业标准", industry="农药",
                     category="废气", sub_category="农药环评",
                     publish_date=datetime(2019, 12, 31), implement_date=datetime(2020, 4, 1),
                     content="规定了农药制造业环境影响评价的技术要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 医药行业标准 ======
            Standard(title="HJ 2025-2013 制药工业污染防治可行技术指南", standard_type="行业标准", industry="医药",
                     category="废水", sub_category="制药废水",
                     publish_date=datetime(2013, 10, 1), implement_date=datetime(2014, 2, 1),
                     content="规定了制药工业废水处理的可行技术。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 2026-2013 吸附法工业有机废气治理工程技术规范", standard_type="行业标准", industry="医药",
                     category="废气", sub_category="制药废气",
                     publish_date=datetime(2013, 10, 1), implement_date=datetime(2014, 2, 1),
                     content="规定了吸附法处理有机废气的工程技术要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 2027-2013 蓄热燃烧法工业有机废气治理工程技术规范", standard_type="行业标准", industry="医药",
                     category="废气", sub_category="制药废气",
                     publish_date=datetime(2013, 10, 1), implement_date=datetime(2014, 2, 1),
                     content="规定了蓄热燃烧法处理有机废气的工程技术要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 石化行业标准 ======
            Standard(title="SH/T 3019-2016 石油化工企业废水处理设计规范", standard_type="行业标准", industry="石化",
                     category="废水", sub_category="石化废水处理",
                     publish_date=datetime(2016, 8, 1), implement_date=datetime(2016, 12, 1),
                     content="规定了石油化工企业废水处理设施的设计要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="SH 3019-2004 石油化工企业给水排水设计规范", standard_type="行业标准", industry="石化",
                     category="废水", sub_category="石化给水排水",
                     publish_date=datetime(2004, 1, 1), implement_date=datetime(2004, 6, 1),
                     content="规定了石油化工企业给水排水工程的设计要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 环境空气监测 ======
            Standard(title="HJ 664-2013 环境空气质量监测点位布设技术规范（试行）", standard_type="行业标准", industry="general",
                     category="环境空气", sub_category="监测布点",
                     publish_date=datetime(2013, 10, 1), implement_date=datetime(2014, 2, 1),
                     content="规定了环境空气监测点位布设的技术要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 653-2013 环境空气气态污染物（SO2、NO2、O3、CO）连续自动监测系统技术要求及检测方法", standard_type="行业标准", industry="general",
                     category="环境空气", sub_category="自动监测",
                     publish_date=datetime(2013, 10, 1), implement_date=datetime(2014, 2, 1),
                     content="规定了气态污染物连续自动监测系统的技术要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 水环境监测 ======
            Standard(title="HJ 91.1-2019 地表水环境质量监测技术规范", standard_type="行业标准", industry="general",
                     category="水环境", sub_category="地表水监测",
                     publish_date=datetime(2019, 11, 12), implement_date=datetime(2020, 1, 1),
                     content="规定了地表水环境质量监测的布点、采样、分析等技术要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 164-2020 地下水环境监测技术规范", standard_type="行业标准", industry="general",
                     category="地下水", sub_category="地下水监测",
                     publish_date=datetime(2020, 11, 11), implement_date=datetime(2021, 3, 1),
                     content="规定了地下水环境监测的布点、采样、分析等技术要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 噪声监测 ======
            Standard(title="HJ 706-2014 声环境功能区监测技术规范", standard_type="行业标准", industry="general",
                     category="噪声", sub_category="噪声监测",
                     publish_date=datetime(2014, 10, 1), implement_date=datetime(2015, 2, 1),
                     content="规定了声环境功能区噪声监测的技术要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 土壤监测 ======
            Standard(title="HJ 25.2-2019 建设用地土壤污染状况调查技术导则", standard_type="行业标准", industry="general",
                     category="土壤", sub_category="调查技术",
                     publish_date=datetime(2019, 11, 12), implement_date=datetime(2020, 1, 1),
                     content="规定了建设用地土壤污染状况调查的技术要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 25.3-2019 建设用地土壤污染风险评估技术导则", standard_type="行业标准", industry="general",
                     category="土壤", sub_category="风险评估",
                     publish_date=datetime(2019, 11, 12), implement_date=datetime(2020, 1, 1),
                     content="规定了建设用地土壤污染风险评估的技术要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 有毒有害物质专项 ======
            Standard(title="GB 37822-2019 挥发性有机物无组织排放控制标准", standard_type="综合标准", industry="general",
                     category="废气", sub_category="VOCs",
                     publish_date=datetime(2019, 5, 10), implement_date=datetime(2019, 7, 1),
                     content="规定了VOCs无组织排放控制要求，适用于石化、化工、包装印刷、工业涂装等行业。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 16297-1996 大气污染物综合排放标准", standard_type="综合标准", industry="general",
                     category="废气", sub_category="大气综合",
                     publish_date=datetime(1996, 11, 1), implement_date=datetime(1997, 1, 1),
                     content="规定了33种大气污染物的排放高度、排放速率和浓度限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 8978-1996 污水综合排放标准", standard_type="综合标准", industry="general",
                     category="废水", sub_category="污水综合排放",
                     publish_date=datetime(1996, 10, 4), implement_date=datetime(1997, 1, 1),
                     content="规定了水污染物排放限值，分为一级、二级、三级标准。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 2000-2010 环境保护产品技术要求 催化燃烧法工业有机废气净化装置", standard_type="行业标准", industry="general",
                     category="废气", sub_category="治理技术",
                     publish_date=datetime(2010, 12, 1), implement_date=datetime(2011, 4, 1),
                     content="规定了催化燃烧法有机废气净化装置的技术要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 新材料行业标准 ======
            Standard(title="GB 31572-2015 电子工业污染物排放标准（半导体）", standard_type="行业标准", industry="新材料",
                     category="废水", sub_category="电子工业废水",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了半导体和电子工业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 31573-2015 电子工业污染物排放标准（显示器件）", standard_type="行业标准", industry="新材料",
                     category="废气", sub_category="电子工业废气",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了显示器件工业大气污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB/T 39736-2020 电子特种气体 高纯氨", standard_type="综合标准", industry="新材料",
                     category="废气", sub_category="电子气体",
                     publish_date=datetime(2020, 6, 2), implement_date=datetime(2020, 12, 1),
                     content="规定了电子级高纯氨的技术要求和测试方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB/T 39737-2020 电子特种气体 高纯氮气", standard_type="综合标准", industry="新材料",
                     category="废气", sub_category="电子气体",
                     publish_date=datetime(2020, 6, 2), implement_date=datetime(2020, 12, 1),
                     content="规定了电子级高纯氮气技术要求和测试方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB/T 39738-2020 电子特种气体 高纯氧气", standard_type="综合标准", industry="新材料",
                     category="废气", sub_category="电子气体",
                     publish_date=datetime(2020, 6, 2), implement_date=datetime(2020, 12, 1),
                     content="规定了电子级高纯氧气技术要求和测试方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 30485-2013 铝工业污染物排放标准", standard_type="行业标准", industry="新材料",
                     category="废水", sub_category="铝工业废水",
                     publish_date=datetime(2013, 12, 31), implement_date=datetime(2014, 7, 1),
                     content="规定了铝工业企业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 30486-2013 稀土工业污染物排放标准", standard_type="行业标准", industry="新材料",
                     category="废水", sub_category="稀土工业废水",
                     publish_date=datetime(2013, 12, 31), implement_date=datetime(2014, 7, 1),
                     content="规定了稀土工业企业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 30487-2013 铅蓄电池工业污染物排放标准", standard_type="行业标准", industry="新材料",
                     category="废水", sub_category="铅蓄电池废水",
                     publish_date=datetime(2013, 12, 31), implement_date=datetime(2014, 7, 1),
                     content="规定了铅蓄电池工业企业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 30488-2013 钴冶炼工业污染物排放标准", standard_type="行业标准", industry="新材料",
                     category="废气", sub_category="钴冶炼废气",
                     publish_date=datetime(2013, 12, 31), implement_date=datetime(2014, 7, 1),
                     content="规定了钴冶炼工业企业大气污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB/T 24717-2020 压力管道元件制造单位质量保证体系要求", standard_type="综合标准", industry="新材料",
                     category="固废", sub_category="压力管道",
                     publish_date=datetime(2020, 6, 2), implement_date=datetime(2021, 1, 1),
                     content="规定了压力管道元件制造单位质量保证体系要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 2547-2016 土壤及地下水污染风险管控 电子工业", standard_type="行业标准", industry="新材料",
                     category="土壤", sub_category="电子土壤",
                     publish_date=datetime(2016, 8, 1), implement_date=datetime(2016, 12, 1),
                     content="规定了电子工业土壤及地下水污染风险管控要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 新能源行业标准 ======
            Standard(title="GB 31573-2015 锂电池工业污染物排放标准", standard_type="行业标准", industry="新能源",
                     category="废水", sub_category="锂电池废水",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了锂电池工业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 31574-2015 太阳能电池工业污染物排放标准", standard_type="行业标准", industry="新能源",
                     category="废气", sub_category="光伏废气",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了太阳能电池工业大气污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB/T 34131-2017 锂离子电池工厂设计规范", standard_type="综合标准", industry="新能源",
                     category="废气", sub_category="锂电工厂",
                     publish_date=datetime(2017, 12, 1), implement_date=datetime(2018, 4, 1),
                     content="规定了锂离子电池工厂设计规范，包括环保设施设计。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB/T 34132-2017 光伏制造企业能源管理体系要求", standard_type="综合标准", industry="新能源",
                     category="废气", sub_category="光伏能源",
                     publish_date=datetime(2017, 12, 1), implement_date=datetime(2018, 4, 1),
                     content="规定了光伏制造企业能源管理体系要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 1182-2021 锂离子电池工业污染物排放标准", standard_type="行业标准", industry="新能源",
                     category="废水", sub_category="锂电池废水",
                     publish_date=datetime(2021, 6, 1), implement_date=datetime(2021, 9, 1),
                     content="规定了锂离子电池工业水污染物排放限值及监测要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 1183-2021 太阳能电池工业污染物排放标准", standard_type="行业标准", industry="新能源",
                     category="废气", sub_category="光伏废气",
                     publish_date=datetime(2021, 6, 1), implement_date=datetime(2021, 9, 1),
                     content="规定了太阳能电池工业大气污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB/T 41366-2022 光伏制造企业清洁生产评价指标体系", standard_type="综合标准", industry="新能源",
                     category="固废", sub_category="光伏清洁生产",
                     publish_date=datetime(2022, 3, 1), implement_date=datetime(2022, 6, 1),
                     content="规定了光伏制造企业清洁生产评价指标体系。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 日用化妆品行业标准 ======
            Standard(title="GB/T 36764-2018 化妆品工厂设计规范", standard_type="综合标准", industry="日用化妆品",
                     category="废水", sub_category="化妆品废水",
                     publish_date=datetime(2018, 10, 1), implement_date=datetime(2019, 3, 1),
                     content="规定了化妆品工厂的设计要求，包括废水处理设施。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 37823-2019 制药工业挥发性有机物排放标准", standard_type="综合标准", industry="日用化妆品",
                     category="废气", sub_category="日化废气",
                     publish_date=datetime(2019, 5, 10), implement_date=datetime(2019, 7, 1),
                     content="规定了制药工业VOCs排放限值，部分适用于日用化妆品行业。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 2029-2013 涂装工程废气治理工程技术规范", standard_type="行业标准", industry="日用化妆品",
                     category="废气", sub_category="涂装废气",
                     publish_date=datetime(2013, 10, 1), implement_date=datetime(2014, 2, 1),
                     content="规定了涂装工程废气治理工程技术要求，适用于日化产品包装涂装。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 复合材料行业标准 ======
            Standard(title="GB/T 36765-2018 复合材料制品企业清洁生产评价指标体系", standard_type="综合标准", industry="复合材料",
                     category="固废", sub_category="复合材料清洁生产",
                     publish_date=datetime(2018, 10, 1), implement_date=datetime(2019, 3, 1),
                     content="规定了复合材料制品企业清洁生产评价指标体系。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 2040-2014 表面涂装（家具制造业）挥发性有机物排放污染防治技术政策", standard_type="行业标准", industry="复合材料",
                     category="废气", sub_category="涂装VOCs",
                     publish_date=datetime(2014, 12, 1), implement_date=datetime(2015, 3, 1),
                     content="规定了表面涂装过程VOCs排放污染防治技术政策。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 化工园区专项标准 ======
            Standard(title="GB/T 38580-2020 化工园区环境与健康风险评估技术指南", standard_type="综合标准", industry="化工园区",
                     category="职业病危害", sub_category="化工园区健康",
                     publish_date=datetime(2020, 8, 1), implement_date=datetime(2020, 11, 1),
                     content="规定了化工园区环境与健康风险评估的技术方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 31571-2015 化工园区危险废物焚烧污染控制标准", standard_type="综合标准", industry="化工园区",
                     category="固废", sub_category="危废焚烧",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了化工园区危险废物焚烧设施的大气污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB/T 35796-2017 化工园区环境风险防控建设技术规范", standard_type="综合标准", industry="化工园区",
                     category="废水", sub_category="园区废水",
                     publish_date=datetime(2017, 12, 1), implement_date=datetime(2018, 4, 1),
                     content="规定了化工园区环境风险防控设施建设技术要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 1076-2020 化工园区集中污水处理设施水污染物排放标准编制技术指南", standard_type="行业标准", industry="化工园区",
                     category="废水", sub_category="园区废水",
                     publish_date=datetime(2020, 9, 1), implement_date=datetime(2020, 12, 1),
                     content="规定了化工园区集中污水处理设施排放标准编制方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 1192-2021 化工园区突发环境事件风险评估技术指南", standard_type="行业标准", industry="化工园区",
                     category="固废", sub_category="风险防控",
                     publish_date=datetime(2021, 6, 1), implement_date=datetime(2021, 9, 1),
                     content="规定了化工园区突发环境事件风险评估技术方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB/T 41367-2022 化工园区地下水污染风险评估技术指南", standard_type="综合标准", industry="化工园区",
                     category="地下水", sub_category="园区地下水",
                     publish_date=datetime(2022, 3, 1), implement_date=datetime(2022, 6, 1),
                     content="规定了化工园区地下水污染风险评估的技术方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 医药行业专项标准（扩展） ======
            Standard(title="HJ 2025-2013 制药工业污染防治可行技术指南", standard_type="行业标准", industry="医药",
                     category="废水", sub_category="制药废水",
                     publish_date=datetime(2013, 10, 1), implement_date=datetime(2014, 2, 1),
                     content="规定了制药工业废水处理的可行技术。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 2027-2013 医药工业废气治理工程技术规范", standard_type="行业标准", industry="医药",
                     category="废气", sub_category="制药废气",
                     publish_date=datetime(2013, 10, 1), implement_date=datetime(2014, 2, 1),
                     content="规定了医药工业废气治理工程技术要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 2028-2013 抗生素类制药工业水污染物排放标准", standard_type="行业标准", industry="医药",
                     category="废水", sub_category="抗生素废水",
                     publish_date=datetime(2013, 10, 1), implement_date=datetime(2014, 2, 1),
                     content="规定了抗生素类制药工业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 2029-2013 激素类制药工业水污染物排放标准", standard_type="行业标准", industry="医药",
                     category="废水", sub_category="激素类废水",
                     publish_date=datetime(2013, 10, 1), implement_date=datetime(2014, 2, 1),
                     content="规定了激素类制药工业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 2030-2013 抗肿瘤类制药工业水污染物排放标准", standard_type="行业标准", industry="医药",
                     category="废水", sub_category="抗肿瘤废水",
                     publish_date=datetime(2013, 10, 1), implement_date=datetime(2014, 2, 1),
                     content="规定了抗肿瘤类制药工业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 2031-2013 兽用药品类制药工业水污染物排放标准", standard_type="行业标准", industry="医药",
                     category="废水", sub_category="兽药废水",
                     publish_date=datetime(2013, 10, 1), implement_date=datetime(2014, 2, 1),
                     content="规定了兽用药品类制药工业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 2032-2013 中药类制药工业水污染物排放标准", standard_type="行业标准", industry="医药",
                     category="废水", sub_category="中药废水",
                     publish_date=datetime(2013, 10, 1), implement_date=datetime(2014, 2, 1),
                     content="规定了中药类制药工业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 2033-2013 医药发酵类制药工业水污染物排放标准", standard_type="行业标准", industry="医药",
                     category="废水", sub_category="发酵制药废水",
                     publish_date=datetime(2013, 10, 1), implement_date=datetime(2014, 2, 1),
                     content="规定了医药发酵类制药工业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 农药行业扩展 ======
            Standard(title="HJ 2046-2014 农药工业水污染物排放标准编制技术指南", standard_type="行业标准", industry="农药",
                     category="废水", sub_category="农药废水",
                     publish_date=datetime(2014, 1, 1), implement_date=datetime(2014, 4, 1),
                     content="规定了农药工业水污染物排放标准编制方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 2047-2014 农药工业废气污染防治技术政策", standard_type="行业标准", industry="农药",
                     category="废气", sub_category="农药废气",
                     publish_date=datetime(2014, 1, 1), implement_date=datetime(2014, 4, 1),
                     content="规定了农药工业废气污染防治技术政策。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 石油天然气行业 ======
            Standard(title="GB 31570-2015 石油天然气开采业污染物排放标准", standard_type="行业标准", industry="石化",
                     category="废水", sub_category="油气开采废水",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了石油天然气开采业水污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="GB 31571-2015 石油天然气精炼业污染物排放标准", standard_type="行业标准", industry="石化",
                     category="废气", sub_category="油气精炼废气",
                     publish_date=datetime(2015, 6, 3), implement_date=datetime(2016, 1, 1),
                     content="规定了石油天然气精炼业大气污染物排放限值。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 环境管理标准 ======
            Standard(title="HJ 2.1-2016 环境影响评价技术导则 总纲", standard_type="行业标准", industry="general",
                     category="环境空气", sub_category="环评总纲",
                     publish_date=datetime(2016, 11, 1), implement_date=datetime(2017, 1, 1),
                     content="规定了环境影响评价的技术总纲。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 2.4-2021 环境影响评价技术导则 声环境", standard_type="行业标准", industry="general",
                     category="噪声", sub_category="噪声环评",
                     publish_date=datetime(2021, 6, 1), implement_date=datetime(2021, 9, 1),
                     content="规定了声环境环境影响评价技术方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 169-2018 建设项目危险废物环境影响评价技术指南", standard_type="行业标准", industry="general",
                     category="固废", sub_category="危废环评",
                     publish_date=datetime(2018, 11, 1), implement_date=datetime(2019, 2, 1),
                     content="规定了建设项目危险废物环境影响评价技术方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 168-2020 环境影响评价技术导则 土壤环境（试行）", standard_type="行业标准", industry="general",
                     category="土壤", sub_category="土壤环评",
                     publish_date=datetime(2020, 12, 1), implement_date=datetime(2021, 3, 1),
                     content="规定了土壤环境环境影响评价技术方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 风险管控标准 ======
            Standard(title="GB 36732-2023 尾矿库环境风险防控技术规范", standard_type="综合标准", industry="general",
                     category="固废", sub_category="尾矿库",
                     publish_date=datetime(2023, 5, 1), implement_date=datetime(2023, 8, 1),
                     content="规定了尾矿库环境风险防控的技术要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 943-2018 地下水污染同位素源解析技术指南", standard_type="行业标准", industry="general",
                     category="地下水", sub_category="地下水监测",
                     publish_date=datetime(2018, 6, 1), implement_date=datetime(2018, 9, 1),
                     content="规定了地下水污染同位素源解析技术方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 917-2017 工业企业土壤和地下水自行监测技术指南", standard_type="行业标准", industry="general",
                     category="土壤", sub_category="自行监测",
                     publish_date=datetime(2017, 11, 1), implement_date=datetime(2018, 2, 1),
                     content="规定了工业企业土壤和地下水自行监测技术方法。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            # ====== 新污染物 ======
            Standard(title="GB/T 41622-2022 新污染物环境风险评估技术体系", standard_type="综合标准", industry="general",
                     category="废水", sub_category="新污染物",
                     publish_date=datetime(2022, 10, 1), implement_date=datetime(2023, 1, 1),
                     content="规定了新污染物环境风险评估技术体系框架。",
                     source_url="https://www.mee.gov.cn/", status="active"),
            Standard(title="HJ 1238-2022 持久性有机污染物环境风险管控技术政策", standard_type="行业标准", industry="general",
                     category="土壤", sub_category="POPs",
                     publish_date=datetime(2022, 3, 1), implement_date=datetime(2022, 6, 1),
                     content="规定了持久性有机污染物的环境风险管控技术要求。",
                     source_url="https://www.mee.gov.cn/", status="active"),
        ]

        total_added = 0
        for s in standards:
            existing = db.query(Standard).filter(Standard.title == s.title).first()
            if not existing:
                db.add(s)
                total_added += 1
        db.commit()
        print(f"标准: 新增 {total_added} 条")

        # 按类别统计
        categories = {}
        for s in db.query(Standard).filter(Standard.status == "active").all():
            cat = s.category
            if cat:
                categories[cat] = categories.get(cat, 0) + 1
        print("按类别统计:")
        for cat, count in sorted(categories.items()):
            print(f"  {cat}: {count} 条")

        # 按行业标准统计
        industries = {}
        for s in db.query(Standard).filter(Standard.status == "active").all():
            ind = s.industry if s.industry else "general"
            industries[ind] = industries.get(ind, 0) + 1
        print("按行业统计:")
        for ind, count in sorted(industries.items(), key=lambda x: -x[1]):
            print(f"  {ind}: {count} 条")

        print(f"总计: {total_added} 条新标准入库")
    finally:
        db.close()


if __name__ == "__main__":
    seed_all()
